### PR TITLE
Fix bug causing urgency to return negative values

### LINKED ISSUE #130: Fix analytics urgency field being able to display negative values
Currently, in the analytics view, the urgency pie chart is able to display a negative percentage, as shown below.

image

### PR DESCRIPTION
**Pull request by marcus-ny**
Fixes #130 

## Changelog

- in `UniqueLoanList`, the `getEarliestReturnDate` method now uses `loan.isOverdue` instead of manual calculation to filter out overdue loans
- In `Analytics`, the `EarliestReturnDate` attribute has been modified to not reflect overdue ones

### CODE REVIEW

File: src/main/java/seedu/address/model/analytics/DashboardData.java [hunk 1]
```diff
@@ -64,11 +64,15 @@ public Float getUrgencyIndex() {
         if (analytics.getEarliestReturnDate() == null || earliestReturnDate == null) {
             return null;
         }
+
         LocalDate target = analytics.getEarliestReturnDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
         LocalDate benchmark = this.earliestReturnDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
         LocalDate now = LocalDate.now();
         long dayDiffBenchmark = benchmark.toEpochDay() - now.toEpochDay();
         long dayDiffTarget = target.toEpochDay() - now.toEpochDay();
+        if (dayDiffTarget == 0) {
```
Comment (kjw142857) [inline src/main/java/seedu/address/model/analytics/DashboardData.java:73]: Good catch!

File: src/main/java/seedu/address/model/person/UniqueLoanList.java [hunk 2]
```diff
@@ -353,7 +354,8 @@ public Date getEarliestReturnDate() {
         Date earliestReturnDate = null;
         for (Loan loan : internalList) {
             if ((earliestReturnDate == null || loan.getReturnDate().before(earliestReturnDate))
-                    && !loan.getReturnDate().before(new Date()) && !loan.isReturned()) {
+                    && !loan.isOverdue() && !loan.isReturned()) {
+                System.out.println(loan.getReturnDate() + " " + loan.isOverdue() + " " + loan.isReturned());
```
Comment (kjw142857) [inline src/main/java/seedu/address/model/person/UniqueLoanList.java:358]: Would you want to remove this `System.out.println` statement? HAHA

**Review by kjw142857 — CHANGES_REQUESTED** [review]
Just one minor nit!

File: src/main/java/seedu/address/model/person/UniqueLoanList.java (hunk 2 above)
Comment (marcus-ny) [reply src/main/java/seedu/address/model/person/UniqueLoanList.java:358]: Oops, missed it. I'll remove the sysout lines

**Review by kjw142857 — APPROVED** [review]
LGTM!
